config/routes.rb
Rails.application.routes.draw do
  resources :queries
  
  root 'queries#new'
end

app/models/query.rb
require 'net/http'

class Query < ActiveRecord::Base
  before_save :replace_spaces

  def get_results
    response = query_service self.term
    @results = []
    count = response["pagination"]["count"].to_i
    (0..count-1).each do |i|
      @results << response["data"][i]["images"]["downsized"]["url"]
    end
    @results
  end

  def query_service(term)
    url = URI.parse("http://api.giphy.com/v1/gifs/search?q=#{term}&api_key=dc6zaTOxFJmzC")
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    JSON.parse res.body
  end

  private

    def replace_spaces
      self.term.gsub!(/\s+/, '+')  
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show, :edit, :update, :destroy]

  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @results = Query.last.get_results rescue []
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(query_params)
    @results = []

    respond_to do |format|
      if @query.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1
  # PATCH/PUT /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to @query, notice: 'Query was successfully updated.' }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query.destroy
    respond_to do |format|
      format.html { redirect_to queries_url, notice: 'Query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_params
      params.require(:query).permit(:term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/queries/_form.html.erb
<%= form_for(@query) do |f| %>
  <% if @query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
      <% @query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :term %>
  </div>
  <div class="actions">
    <%= f.submit "Search"%>
  </div>
<% end %>

app/views/queries/edit.html.erb
<h1>Editing query</h1>

<%= render 'form' %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

app/views/queries/index.html.erb
<h1>Listing queries</h1>

<table>
  <thead>
    <tr>
      <th>Term</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.term %></td>
        <td><%= link_to 'Show', query %></td>
        <td><%= link_to 'Edit', edit_query_path(query) %></td>
        <td><%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query', new_query_path %>

app/views/queries/new.html.erb
<%= render 'form' %>

<% @results.each do |result| %>
  <img src="<%= result %>"/>
<% end %>

app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @query.term %>
</p>

<%= link_to 'Edit', edit_query_path(@query) %> |
<%= link_to 'Back', queries_path %>